import './globals.css'
import './assets/styles.scss'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {Header} from './components/header/header'
import {MyFooter} from './components/footer/footer'

import 'bootstrap/dist/css/bootstrap.css';
import 'font-awesome/css/font-awesome.min.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
          {children}
          <MyFooter/>
        </body>
    </html>
  )
}
